---
abstract: 'Perl bindings for k (aka q, aka kdb, aka kx)'
author:
  - 'Whitney Jackson C<< <whitney@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  File::Which: 0
  FindBin: 0
  Test::Exception: 0
  Test::More: 0
  Test::TCP: 0
configure_requires:
  ExtUtils::Depends: 0
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl_5
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: K
no_index:
  directory:
    - inc
    - t
requires:
  Math::Int64: 0
  Moose: 0
  namespace::autoclean: 0
  perl: 5.10.0
resources:
  repository: http://github.com/wjackson/k-perl
version: 0.08
